apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: devops-platform

images:
  - name: ghcr.io/monjju/devops-platform
    newTag: 69ceca961fdd7cfcb4746d565e0e860b1103b6d7
