apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: devops-platform

images:
  - name: ghcr.io/monjju/devops-platform
    newTag: 68bb07b5aad4ffe348b0801a32cea61be278570b
