apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: devops-platform

images:
  - name: ghcr.io/monjju/devops-platform
    newTag: a3d5982e4bd37dcaccd4881d272b3a6b9df33a0c
